import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom'
import {Activity,AlertTriangle,ArrowLeft,ArrowRight,BarChart3,Bell,CalendarDays,CheckCircle2,ChevronDown,Clock3,FileCheck2,Gauge,LayoutDashboard,ListChecks,MapPinned,RefreshCw,Search,Settings2,ShieldCheck,Sparkles,TrainFront,TriangleAlert,UserCircle,Wifi} from 'lucide-react'
import './styles.css'

const API='http://127.0.0.1:8000'

type RequestItem={id:string;department:string;task:string;asset:string;section:string;date:string;start:string;end:string;duration:number;blockType:string;priority:number;requestStatus:string;authorizationStatus:string;power:boolean}

const mockRequests:RequestItem[]=[
 {id:'REQ-2025-089',department:'ENG · Track Machine',task:'T00022 · Deep Screening Ballast',asset:'Track S02-UP-KM48 (Continuous Welded Rail)',section:'S02 (GZB - ALJN)',date:'Today',start:'18:00',end:'20:00',duration:120,blockType:'Traffic Block',priority:92,requestStatus:'OPTIMIZED (In Plan)',authorizationStatus:'Pending Controller Approval',power:false},
 {id:'REQ-2025-091',department:'S&T · Signaling & Telecom',task:'T00035 · Point Machine Overhaul',asset:'Point 104A GZB Yard Interlock',section:'S01 (Delhi Inbound)',date:'Tmrw',start:'02:00',end:'04:00',duration:120,blockType:'Traffic Block',priority:74,requestStatus:'QUEUED FOR OPTIMIZATION',authorizationStatus:'Not Submitted for Clearance',power:true},
 {id:'REQ-2025-093',department:'TRD · Traction Distribution',task:'T00042 · OHE inspection',asset:'OHE Mast S03-KM17',section:'S03 (ALJN - ETW)',date:'Today',start:'21:00',end:'23:00',duration:120,blockType:'Power Block',priority:84,requestStatus:'VALIDATED',authorizationStatus:'Not Submitted for Clearance',power:true}
]

async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(API+path,options);if(!r.ok)throw new Error(`${r.status}`);return r.json()}

function App(){
 const loc=useLocation(); const nav=useNavigate();
 const [requests,setRequests]=useState<RequestItem[]>(mockRequests); const [connected,setConnected]=useState(false)
 useEffect(()=>{api('/api/v1/database/health').then(()=>setConnected(true)).catch(()=>setConnected(false));api<any[]>('/api/v1/requests').then(data=>{if(Array.isArray(data)&&data.length){setRequests(data.map((x:any)=>({id:x.block_request_id,department:x.department_id,task:x.task_id,asset:x.asset_id||'Asset linked to maintenance task',section:x.section_id,date:x.requested_date,start:x.preferred_start,end:x.preferred_end,duration:x.minimum_duration_min,blockType:x.block_type,priority:Number(x.priority_score||0),requestStatus:x.request_status,authorizationStatus:x.authorization_status,power:Boolean(x.power_block_required)})))}}).catch(()=>{})},[])
 const screen=loc.pathname
 const navItems=[['/','Overview',LayoutDashboard],['/requests','Requests',ListChecks],['/planner','Planner',CalendarDays],['/recommended','Recommended',Sparkles],['/audit','More / Audit',ShieldCheck]] as const
 return <div className="appShell">
   <header className="topbar"><div className="brand"><div className="brandMark"><TrainFront size={17}/></div><div><b>IR-ABPS</b><span>SIH26027</span><small>Northern Rly / DLI Div</small></div></div><div className="topActions"><span className="env">⌁ Synthetic Data | Demo Environment</span><span className="live">LIVE 4.12</span><button className="iconBtn"><Bell size={16}/><i/></button><button className="profile"><UserCircle size={19}/></button></div></header>
   <main className="page">{screen==='/'?<Overview connected={connected} onRequests={()=>nav('/requests')}/>:screen==='/requests'?<Requests requests={requests} onOpen={r=>nav('/requests/'+r.id)} onNew={()=>nav('/requests/new')}/>:screen.startsWith('/requests/')?<RequestDetail requests={requests} onBack={()=>nav('/requests')}/>:screen==='/planner'?<Planner/>:screen==='/recommended'?<Recommended/>:<Audit/>}</main>
   <nav className="bottomNav">{navItems.map(([path,label,Icon])=><button key={path} className={screen===path||((path==='/requests')&&screen.startsWith('/requests'))?'active':''} onClick={()=>nav(path)}><Icon size={18}/><span>{label}</span></button>)}</nav>
 </div>
}

function SectionTitle({children,action}:{children:React.ReactNode;action?:React.ReactNode}){return <div className="sectionTitle"><h2>{children}</h2>{action}</div>}
function Overview({connected,onRequests}:{connected:boolean;onRequests:()=>void}){
 const [running,setRunning]=useState(false);const [result,setResult]=useState<any>(null)
 const run=async()=>{setRunning(true);try{const r=await api('/api/v1/optimization/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planning_date:'2026-09-02',block_type:'TRAFFIC'})});setResult(r)}catch{setResult({status:'DEMO',assigned_count:6,total_priority:444.8})}finally{setRunning(false)}}
 return <>
  <div className="context"><div><span className="eyebrow">OPERATIONAL SECTION</span><b>S02: Ghaziabad → Tundla</b><span className="select">⌄</span><p><Clock3 size={12}/> Horizon: 24h (Today)</p></div><div className="sync"><Wifi size={13}/>{connected?'API Connected':'Demo Mode'} <button><RefreshCw size={13}/></button></div></div>
  <div className="guardrail"><ShieldCheck size={19}/><div><b>AI Planning Guardrail Active <span>Rule 4.12</span></b><small>AI recommends. Railway personnel review, modify and approve all corridor possession windows.</small></div></div>
  <div className="kpis"><Kpi title="Critical Maint." value="4" note="Overdue track gang" tone="danger" badge="4 Urgent"/><Kpi title="Overdue Tasks" value="2" note="OHE + S&T impact" tone="warn" badge="2 Alerts"/><Kpi title="Clear Windows" value="6" note="Optimal 120+ min" tone="good" badge="6 Slots"/><Kpi title="Block Requests" value="9" note="Eng + S&T + TRD" tone="neutral" badge="9 Queued"/><Kpi title="Allocated Plan" value={result?.assigned_count||7} note="No conflict lock" tone="good" badge="Ready"/><Kpi title="Restrictions" value="3" note="Km 42, 68, 104" tone="warn" badge="3 TSR/PSR"/></div>
  <SectionTitle action={<span className="tinyTag">UP & DN Lines</span>}>Corridor Operational Strip</SectionTitle>
  <div className="timeline"><div className="legend"><span><i className="dot train"/>Express & Freight</span><span><i className="dot maint"/>Planned Maint.</span><span><i className="dot conflict"/>Conflict</span><span><i className="dot restr"/>TSR / Caution</span><span><i className="dot free"/>Free Window</span></div><div className="hours">{['12','13','14','15','16','17','18','19','20','21','22','23'].map(h=><span key={h}>{h}:00</span>)}</div><Track name="UP Main (Track 1)" items={[['13:10','15:00','#dce5f5','UP 12306 Shatabdi'],['14:00','15:00','conf','Overlap!'],['18:00','20:00','maint','ENG Gang R01 (Tamp)'],['21:00','23:00','free','Open Window (120m)']]}/><Track name="DN Main (Track 2)" items={[['14:30','15:30','restr','PSR 30k (km42)'],['17:00','20:00','train','#12410 Gomti Exp'],['20:30','22:30','train','CONCOR Freight']]}/><div className="timelineAlert"><TriangleAlert size={14}/>Overlap: UP Track km 48.2 (14:30). Shatabdi trail headway breach.<button>Resolve</button></div></div>
  <div className="healthCard"><div className="healthCircle">94%<small>HEALTH</small></div><div className="healthStats"><div><span>Tasks Covered</span><b>18 / 22</b><em>Overdue Reduction <strong>-65%</strong></em></div><div><span>Critical Coverage</span><b>100%</b><em>Punctuality Impact <strong>&lt; 4 min</strong></em></div></div><span className="grade">Optimal Grade A</span></div>
  <div className="topology"><div><small>SIMULATED NETWORK TOPOLOGY</small><b>GZB → ALJN → TDL Automatic Territory</b></div><span>194.5 Km</span></div>
  <button className="runBtn" onClick={run}>{running?<><RefreshCw className="spin" size={17}/> Running Optimization Engine...</>:<><Sparkles size={17}/> Run Optimization Engine</>}</button>
  <button className="recommendBtn" onClick={()=>onRequests()}><Sparkles size={13}/> Review {result?.assigned_count||7} New Recommendations <b>7</b></button>
  <div className="demoNote"><Activity size={12}/> Simulated Northern Railway Division Environment · SIH26027 Synthetic Build</div>
 </>
}
function Kpi({title,value,note,tone,badge}:{title:string;value:React.ReactNode;note:string;tone:string;badge:string}){return <div className={'kpi '+tone}><div><span>{title}</span><b>{value}</b><small>{note}</small></div><em>{badge}</em></div>}
function Track({name,items}:{name:string;items:string[][]}){return <div className="track"><b>{name}</b><div className="trackArea">{items.map(([s,e,c,t],i)=><div key={i} className={'bar '+c} style={{left:`${(parseInt(s)-12)*8.33}%`,width:`${Math.max(5,(parseInt(e)-parseInt(s))*8.33)}%`}}>{t}</div>)}</div></div>}

function Requests({requests,onOpen,onNew}:{requests:RequestItem[];onOpen:(r:RequestItem)=>void;onNew:()=>void}){return <>
 <div className="requestHead"><div><h1>My Block Requests <small>{requests.length} Total</small></h1><p>↔ DLI-GZB-ALJN Slot Window: Night corridor opens 23:30 IST</p></div><button className="newBtn" onClick={onNew}>＋ New Block</button></div>
 <div className="searchRow"><div className="search"><Search size={16}/><input placeholder="Search Task, Block ID, KM mark..."/></div><div className="deptTabs"><button>ENG</button><button>S&T</button><button>TRD</button></div></div>
 <div className="filters">{['All ('+requests.length+')','Draft (1)','Validated (2)','Queued (3)','Optimized (4)','Approved (2)'].map((x,i)=><button className={i===0?'selected':''} key={x}>{x}</button>)}</div>
 <div className="dual"><b>ⓘ DUAL GUARDRAIL ARCHITECTURE</b><span>Algorithmic Optimization checks track conflicts, but a block is <strong>NOT AUTHORIZED</strong> until formally granted by the Section Controller (SCR).</span></div>
 <div className="cards">{requests.map(r=><RequestCard key={r.id} r={r} onOpen={()=>onOpen(r)}/>)}</div>
 </>}
function RequestCard({r,onOpen}:{r:RequestItem;onOpen:()=>void}){return <article className="requestCard"><div className="reqTop"><div><span className="dept">{r.department}</span><b>{r.id}</b></div><span className={'priority '+(r.priority>=85?'critical':'high')}>● {r.priority>=85?'CRITICAL':'HIGH'}</span></div><div className="taskLine"><b>{r.task}</b><span>Asset: {r.asset}</span></div><div className="reqGrid"><span>⌖ {r.section}</span><span>◷ {r.date} {r.start} - {r.end}</span></div><div className="reqMeta"><span>Window: {r.duration} mins</span><span>{r.blockType} (Power: {r.power?'Yes':'No'})</span></div><div className="state"><span>⚙ Request State:</span><b>{r.requestStatus}</b></div><div className="state"><span>◉ SCR Clearance:</span><em>{r.authorizationStatus}</em></div><div className="cardActions"><button onClick={onOpen}>View Pre-Check</button><button onClick={onOpen}>Track Status</button></div></article>}

function RequestDetail({requests,onBack}:{requests:RequestItem[];onBack:()=>void}){const r=requests[0];const [pre,setPre]=useState<any>(null);const [loading,setLoading]=useState(false);const run=async()=>{setLoading(true);try{setPre(await api('/api/v1/precheck',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({department_id:'ENG',section_id:'S02',location_id:'L00002',asset_id:'A00002',maintenance_task_id:'T00002',preferred_date:'2026-09-02',preferred_start_time:'14:00',preferred_end_time:'16:30',minimum_duration_minutes:120,block_type:'TRAFFIC',power_block_required:true,resource_ids:['R01']})}))}catch{setPre({status:'WARNING',checks_total:7,checks_passed:6,warnings:1,blocks:0,suggested_windows:[]})}finally{setLoading(false)}};return <>
 <button className="back" onClick={onBack}><ArrowLeft size={17}/> Request Detail <span>IR-ABPS · DLI Div</span></button><div className="steps"><b>✓<small>Details</small></b><b className="current">2<small>Time & Block</small></b><b>3<small>Pre-check</small></b><b>4<small>Submit</small></b></div>
 <div className="detailHero"><div><span>T00022</span><span>ENG Dept</span><h2>Track UP-S02-KM48 (Turnout 12A)</h2><p>Ultrasonic Flaw Detection (USFD) micro-crack detected. Immediate block maintenance mandated.</p></div><em>⚠ Score 92/100 · Overdue 2d</em></div>
 <section className="formCard"><div className="formHead"><h2>Block Specifications</h2><span>⇄ Step 2 of 4</span></div><label>OPERATIONAL SECTION<div className="field locked">⚯ Section S02 (Ghaziabad - Aligarh) <span>🔒</span></div></label><div className="two"><label>PREFERRED DATE<div className="field">▣ Today (24 Oct)</div></label><label>BLOCK TARGET<div className="field"><b>150 min</b><small>Min: 120m</small></div></label></div><label>PREFERRED TIME WINDOW<div className="two"><div className="field">Start <b>14:00</b> ◷</div><div className="field">End <b>16:30</b> ◷</div></div></label><label>BLOCK TYPE<div className="seg"><button>Traffic</button><button>Power</button><button className="active">Integrated</button></div></label><div className="toggle"><b>ϟ 25kV OHE Power Isolation</b><span>Requires Traction Substation Permit <i>●</i></span><button>●</button></div><label>ALLOCATED GANG & ROLLING PLANT<div className="chips"><span>Gang R01 (P-Way) ×</span><span>BCM Machine 614 ×</span><span>S&T Escort ×</span><button>＋ Add</button></div></label><label>METHODOLOGY & TSR PLAN<div className="textarea">Deep screening and sleeper renewal under cautionary speed (30 km/h).</div></label><button className="runPre" onClick={run}>{loading?<RefreshCw className="spin"/>:<Sparkles size={16}/>} Run Smart Pre-Check</button><small className="helper">⟳ Simulates dynamic conflict solver against live IR timetable, scheduled rakes, and speed restrictions.</small></section>
 <div className="feas"><b>● Live Feasibility Result</b>{pre&&<span>{pre.status} · {pre.checks_passed}/{pre.checks_total} checks passed · {pre.blocks} blocking conflicts</span>}<em>{pre?'1 Conflict':'1 Conflict'}⌄</em></div>
 </>}

function Planner(){return <div className="placeholder"><CalendarDays size={42}/><h1>Block Planner</h1><p>Timeline planning surface is next. It will consume COA windows, train events, restrictions, resources and optimizer assignments.</p><button className="runBtn">Open Planning Horizon</button></div>}
function Recommended(){return <div className="placeholder"><Sparkles size={42}/><h1>Recommended Plan</h1><p>Explainable optimizer recommendations will appear here, with assigned tasks, reasons and unscheduled-task explanations.</p></div>}
function Audit(){return <div className="placeholder"><ShieldCheck size={42}/><h1>Execution & Audit</h1><p>Authorization, execution status and immutable planning decisions will be tracked here.</p></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
